Ft admin panel jurc413q
Eli250/my-brand pull request #7
Opened 2021-12-28 18:37 UTC by Eli250

#### What does this PR do?

Update admin panel

#### Description of Task to be completed?

This PR adds features to admin pane that were not present before.
#### How should this be manually tested?

This should be tested by checking if admin can view all created posts and see the total counts on dashboard.

#### What are the relevant pivotal tracker stories?

ZNbdHQuX

#### Screenshots:

![Screenshot from 2021-12-28 20-36-21](https://user-images.githubusercontent.com/60324751/147596645-7f7a78f3-234d-4d74-bc3f-dfa98af37d4f.png)
![Screenshot from 2021-12-28 20-36-26](https://user-images.githubusercontent.com/60324751/147596658-b0cd3b36-b4ef-41b3-bc10-84d8d0e57ea1.png)

#### Questions
N/A
:

2021-12-29 07:56 UTC, ncutixavier requested changes

2021-12-29 07:56 UTC, ncutixavier commented on UI/script.js
> +  // Toggle menu / navbar script
Remove Jquery in your code

2021-12-29 07:56 UTC, ncutixavier commented on UI/script.js
> +});
Remove Jquery

2021-12-29 17:18 UTC, ncutixavier commented on UI/script.js
> +});
Change your PR title to follow naming convention

2021-12-30 11:54 UTC, Eli250 reviewed
I have removed all jQuery files and replaced with pure javaScript.
You can review them in my recent push.

###Screenshots
![Screenshot from 2021-12-30 13-52-48](https://user-images.githubusercontent.com/60324751/147749668-df3bb457-ab1f-40d1-9a4d-95d498480eee.png)
![Screenshot from 2021-12-30 13-52-32](https://user-images.githubusercontent.com/60324751/147749727-67777146-319f-4cb7-8196-4a60d915ed4f.png)

2022-01-10 06:36 UTC, ncutixavier approved these changes

2022-01-10 06:37 UTC, merged